### ISSUE TITLE
Allow subscriptions to listen to "regular" PubSub events

### ISSUE THREAD

**Issue by hauleth** [absinthe-graphql/absinthe#1251]
Right now [`subscription/2`](https://hexdocs.pm/absinthe/1.7.1/Absinthe.Schema.html#subscription/1) feature is focused on events coming up from within GraphQL API (aka it listens to mutations). Though it would be really handy to be able to send events from outside of the GraphQL API definition as well. Right now the only way to do so is to use [`Absinthe.Subscription.publish/3`](https://hexdocs.pm/absinthe/1.7.1/Absinthe.Subscription.html#publish/3), but that forces our core system to be aware of the API that we define (as we cannot use just [`Phoenix.PubSub.broadcast/4`](https://hexdocs.pm/phoenix_pubsub/2.1.3/Phoenix.PubSub.html#broadcast/3)). This make it painful when the GraphQL do not have mutations (in my case the API is just a view into the data in the blockchain, so I expose events coming from the outside world) or when we have multiple interfaces and GraphQL is just one of them.

Right now there are 2 ways (both hacky) to achieve that:

- spawn process that will receive PubSub messages and then republish them using Absinthe API
- use `telemetry` or similar dispatch system to publish events and then dynamically attach Absinthe event dispatcher

In ideal world there would be a way to publish PubSub event from the core and then just allow Absinthe subscription to listen on such events.

**Comment by benwilson512** [comment]
> just allow Absinthe subscription to listen on such events.

Hey @hauleth this bit here is the main challenge. Absinthe would need to spawn like a pool of processes or something that would be listening for your publications, and then calling `publish/3`. `publish/3` is pretty non optional because only a small part of what it does is the actual message sending, the majority of its work is fetching down the correct docs to publish out and actually execute them.

Framed that way, I'm 99% certain that this could just start as an external library like `AbsintheForwarder` or something which handles this. I'd be open down the line to looking at integrating this sort of thing into Absinthe proper but there's a bunch of open questions about how people want to handle back pressure, pool management, and other related things.
