### ISSUE TITLE
Allow subscription config errors to return spec compliant errors

### ISSUE THREAD

**Issue by bryanjos** [absinthe-graphql/absinthe#1340]
Currently subscription config functions expect either `{:ok, config}` or `{:error, msg}` to be returned. In the error case, this is what's returned ultimately:

```elixir
%{errors: [%{message: msg}]}
```

We would like to send spec compliant errors with extra information from the config errors. 

Right now if we return the following from config

```elixir
{:error, %{extensions: %{code: "FAILED"}, message: "failed"}}
```

We get

```elixir
%{errors: [%{message: %{extensions: %{code: "FAILED"}, message: "failed"}}]}
```

Which breaks some tools that expect spec compliant errors.

There are a couple of ways we've thought about fixing it and could use some feedback before making a PR.

The first way would be to update `Absinthe.Phase.Document.Result` to look for a map in the `message` property of the `Absinthe.Phase.Error` struct created and return what's there as the error.

So returning `{:error, %{extensions: %{code: "FAILED"}, message: "failed"}` from the config function would give

```elixir
%{errors: [%{extensions: %{code: "FAILED"}, message: "failed"}]}
```

The second way we were thinking is updating `Absinthe.Phase.Subscription.SubscribeSelf` to let config return a 3-tuple, `{:error, msg, extra}` and put the `extra` there onto the `extra` property of the `Absinthe.Phase.Error` struct created.

With that, and with `spec_compliant_errors` set to true, if `{:error, "failed", %{code: "FAILED"}` is returned, you would get the above as well.

Or some other way we aren't thinking of.

**Comment by michaelcaterisano** [comment]
Thanks @bryanjos! We've already discussed, but I'll add my thoughts here as well.

My take is that the `config/2` function's API should match the resolver API. That is, it should support the same kind of error tuples. Currently, resolvers allow returning `{:error, "message"}` or `{:error, map}`, where map is `%{message: "message", extensions: %{}}`. https://github.com/absinthe-graphql/absinthe/commit/32db847a137834e618d6f66751b1fa3bcdc4a5fe introduced a `spec_compliant_errors` option, which, when set to true, creates a map like the one above, with "extra errors" being added to the extensions key. I think the idea is for Absinthe to help ensure that errors are spec compliant, but as the PR mentions, the change needs to be opt-in because it's breaking. I also wasn't able to find this option in the docs, but maybe I missed it.

My take is that, while this option is convenient, it's a bit surprising that Absinthe reformats errors in this way. A simpler approach would be to make the `config/2` function's api match a resolver's api, so that there's _one way_ to return errors to clients. This means developers are responsible for returning spec-compliant errors, but that seems reasonable to me.

If instead folks want to go the `spec_compliant_errors` option route, we should make sure it's well documented.

**Comment by bryanjos** [comment]
Knowing the history now, I think I'd back what @michaelcaterisano suggests.

**Comment by bryanjos** [comment]
Made a PR #1341

**Comment by dgvncsz0f** [comment]
👋🏼 folks, I wonder if there is any method to revert to the old behaviour, such as a flag/config. We have many client apps that are very hard to update and depend on the previous error format 🙈 I couldn't find any, but I could very well be missing something.

Also, considering this was a breaking change, wouldn't it be better to bump the major version instead? I wasn't expecting a breaking change from a minor version update. 

1.7.9 contains a bugfix that we need, but this breaking change prevents us from updating.
