### ISSUE TITLE
Duplicate Type Declaration with import_types

### ISSUE THREAD

**Issue by stephenbaldwin** [absinthe-graphql/absinthe#176]
When sharing a type across multiple fields and using import_fields to import those fields, absinthe crashes due to duplicate type declaration.

```
defmodule Types do
  use Absinthe.Schema.Notation

  object :shared_type, do: field(:bar, :string)
end

defmodule Field1 do
  use Absinthe.Schema.Notation

  import_types Types

   object :field1 do
     field :example1, :shared_type
   end
end

defmodule Field2 do
  use Absinthe.Schema.Notation

  import_types Types

   object :field2 do
     field :example2, :shared_type
   end
end

defmodule GraphQL do
  use Absinthe.Schema

  import_types Field1
  import_types Field2

  query do
    import_fields :field2
    import_fields :field1
  end
end

**Comment by benwilson512** [comment]
So, this is less of a bug and more of a general limitation. I'm pretty sure it doesn't actually involve the import_fields bit at all. If you have Foo import_types Baz, and Bar import Baz, and then Schema import Foo and Bar, it's gonna have Baz in there twice. This is because types are not imported lazily but eagerly.

Not sure if there's an easy solution here that isn't predicated on a complete re-work of how type imports work.

**Comment by stephenbaldwin** [comment]
What if we did away with import_types all together and made type definition global?

**Comment by stephenbaldwin** [comment]
happy to help and contribute code where I can

**Comment by benwilson512** [comment]
Global in what sense? We have to be able to support different schemas w/ completely different types.

**Comment by stephenbaldwin** [comment]
Is there a use case where it needs to be able to handle completely different schemas in one implementation? I could see how this would get infinitely more difficult if there is

**Comment by benwilson512** [comment]
You mean completely different schemas in a single project? Yes, people will have public schemas and private schemas quite regularly.

I'm actually still not sure how global types would even work. Types are built as functions on a module. If I reference type `:foo`, what module do I go looking for to call `__absinthe_type__(:foo)` on?

**Comment by benwilson512** [comment]
Actually I have an idea. one sec

**Comment by stephenbaldwin** [comment]
The other option is to stop referencing types through atoms and require explicit pathing:

```
defmodule Foo.Bar do
  object :baz, do: field(:foo, :string)
end

defmodule Schema do
  query do
    field :example, Foo.Bar.baz
   # or 
   field :example, Foo.Bar.type(:baz)
  end
end
```

**Comment by benwilson512** [comment]
The following works: 
```elixir
defmodule Types do
  use Absinthe.Schema.Notation

  object :shared_type, do: field(:bar, :string)
end

defmodule Field1 do
  use Absinthe.Schema.Notation
   object :field1 do
     field :example1, :shared_type
   end
end

defmodule Field2 do
  use Absinthe.Schema.Notation
   object :field2 do
     field :example2, :shared_type
   end
end

defmodule GraphQL do
  use Absinthe.Schema

  import_types Types
  import_types Field1
  import_types Field2

  query do
    import_fields :field2
    import_fields :field1
  end
end
```

The reason this works is that the validations only happen on the actual schema module.

**Comment by stephenbaldwin** [comment]
Yeah I got this to work this way as well, but doesn't this feel a little like a work around? shouldn't the files implementing the objects and fields be in charge of importing the types?

**Comment by benwilson512** [comment]
Possibly. Everything gets baked in at compile time however which does make this very hard. When importing Field2 it's possible we could go through each type and make sure it isn't already imported from elsewhere. It does get a bit wonky though cause in theory you could have types of the same name imported from 2 different places and then instead of giving you a nice error it'll just silently pick the first one.

With respect to the current functionality I think it'll make the most sense if you think about it all working to populate the Schema module. At the end of the day it's all one put inside one namespace (that's how GraphQL works) and that namespace is the schema.

**Comment by stephenbaldwin** [comment]
Thanks Ben

**Comment by benwilson512** [comment]
We could definitely document this better. If you're feeling adventurous and want to cover a simplified version of this scenario on the `import_types` doc via a PR it'd be more than welcome!
