### ISSUE TITLE
Using LanguageConventions with custom Resolvers

### ISSUE THREAD

**Issue by Axxiss** [absinthe-graphql/absinthe#262]
I started to play around with graphql and absinthe, currently I'm struggling to make the backend snake case conversion to camel case to work. I have the following type

``` elixir
  object :profile do
    field :first_name, non_null(:string)
  end
```

this is what my custom resolver is returning after retrieving the info from an external API.

``` elixir
{:ok, %{"first_name" => "John", "id" => 1}}
```

In order to do the conversion to camel case should I expect to get `LanguageConventions` automatically applied to my result or should I do it by hand for each resolver response?

**Comment by Axxiss** [comment]
Just found out what is going on, it's all about the key format. My result is a map with strings as keys while absinthe is doing the look up with atoms as keys.

What are your thoughts about including string look up on resolver's result?

**Comment by bruce** [comment]
@Axxiss This comes up relatively often -- sadly it's not a particularly well-documented gotcha.

For performance reasons, Absinthe has to have a default --  it wouldn't make sense for Absinthe to check atoms and strings for every single field -- and atoms make the most sense, given common use with accessing values from structs (eg, Ecto records).

For resolvers that need to retrieve data from string-keyed sources (MongoDB results is a common case), however, you either need to define your own resolvers instead of using the default, like this:

```elixir
object :foo do
  field :bar, :string do
    resolve fn foo, _, _ ->
      {:ok, Map.get(foo, "bar")}
    end
    # do this over and over...
  end
end
```

... which is of course a pain to do for _every simple field_. Instead, you can set your own default resolver at the schema level to do whatever you want. Here's one that should work for your case, by default looking up field values by string keys:

```elixir
defmodule MyApp.Schema do
  use Absinthe.Schema

  default_resolve fn source, _, %{definition: field} ->
    {:ok, Map.get(source, field.name)}
  end

  # The rest of your schema

end
```

Let me know if there's anything else we can do to help.

(BTW, we're pretty active on our Slack channel with other users if you have questions, etc; details here: http://absinthe-graphql.org/community/)
