### ISSUE TITLE
not able to cast map with arrow key 

### ISSUE THREAD

**Issue by piyushcoader** [absinthe-graphql/absinthe#268]
I have data coming from db with jsonb column and Ecto encodes then into map as 
` %{links: %{"url" => "abc.com", "format" => "format1" }}`

so i tried to match the data with equivalent schema object
``` 
 object :uploads do
      field :links, :links_type
end
```

the links_type object looks like 

```
object :links_type do
  field :url, :string
  field :format, :string
end
 
  
```
its returning null result but if i change map into atoms 
`%{links: %{url: "abc.com", ....}}`
it works fine
I think its because ` {:ok, Map.get(parent, field_name)}` is not able to find value of that key 
how can i pass resolver function to match key -> parent?

**Comment by benwilson512** [comment]
Hey there! There is already a discussion happening on the elixir forum for this issue that I think you started. I think it will be best to continue the discussion there.

**Comment by Overbryd** [comment]
@benwilson512 would be nice to [link the discussion here](https://elixirforum.com/t/serialisation-atoms/4879/4)...
It seems a bit odd to me to resolve issues with this codebase outside Github issues.

For everybody else, in case you come from Google and you are wondering how to resolve that issue:

```elixir
def middleware([], %{identifier: field_identifier}, %{identifier: :config}) do
  [{Absinthe.Middleware.MapGet, Atom.to_string(field_identifier)}]
end
def middleware(middleware, _, _) do
  middleware
end
```

**Comment by Overbryd** [comment]
@benwilson512 do you mind commenting on how to resolve this issue with Absinthe `~> 1.4`?

**Comment by benwilson512** [comment]
> It seems a bit odd to me to resolve issues with this codebase outside Github issues.

This isn't an issue with this code base. This is a matter of educating the user, and forums are a great place for that. I'll make sure to add an update the forum post. 

The function you're looking for is this: https://hexdocs.pm/absinthe/Absinthe.Schema.html#replace_default/4 and there's also further elaboration here: https://hexdocs.pm/absinthe/Absinthe.Middleware.html#module-default-middleware

**Comment by Overbryd** [comment]
This is what I did to get stringified key access by default on objects for Absinthe `~> 1.4`. Please don't break it again. Also it seems pretty verbose, for such a common task.

```elixir
  def middleware(middleware, %{identifier: identifier} = field, object) do
    string_identifier = Atom.to_string(identifier)
    middleware_spec = {{__MODULE__, :get_string_key}, string_identifier}
    Absinthe.Schema.replace_default(middleware, middleware_spec, field, object)
  end
  def middleware(middleware, _field, _object) do
    middleware
  end

  def get_string_key(%{source: source} = res, key) do
    %{res | state: :resolved, value: Map.get(source, key)}
  end
```

@benwilson512 do you know of any better way to handle this?

**Comment by benwilson512** [comment]
Aight so a couple of things. It is our goal every release to minimize breaking changes. Nonetheless, this goal is one of many goals, and there have been and will continue to be times where meeting those goals requires a breaking change.

When we have to make a breaking change, we do everything we can to be transparent about it. This particular change can be found in the CHANGELOG: https://github.com/absinthe-graphql/absinthe/blob/master/CHANGELOG.md#v140 This not only notes the change, but includes a link to the new solution, and it also includes a link to the original PR that motivated this change. I'm not going to repeat the contents of that PR here, but if you have any concrete questions about it you're more than welcome to follow up.

The forum post you link to was started on May 1st, so it is unlikely to be the same one referenced by this issue on Feb 16th.

Per the solution linked to both here and in the changelog, you can eliminate 3 lines from what you have there since the extra middleware clause is unnecessary. In fact we can remove another line `string_identifier = Atom.to_string(field_identifier)` if we're doing a direct comparison to what you had originally, giving us
```elixir
 def middleware(middleware, %{identifier: identifier} = field, object) do
  middleware_spec = {{__MODULE__, :get_string_key}, Atom.to_string(identifier)}
  Absinthe.Schema.replace_default(middleware, middleware_spec, field, object)
end
```

There is definitely an element of verboseness here, but ultimately I'm pretty happy with where that sits relative to trade offs around clarity and flexibility. There are potentially a million different variations of this question. Shat if the keys aren't merely strings but also strings and upper cased, or camel cased? What if it isn't a map at all but some other datastructure. Each of these can be clearly and plainly handled via the exact same pattern.

The move to `Absinthe.Schema.replace_default` is actually very important, because it frees up Absinthe to change the underlying default resolver without affecting user code or introducing additional breaking changes. This in fact already obtains, in that the default resolver for subscription fields is simply a pass through.

Ultimately, it went from 2 very simple clauses weighing in on 6 lines to 1 slightly more complex clause weighing in at 4. More to the point, it eliminates a broad class of bugs that were easy to introduce if you weren't careful with how middleware was applied. For more rationale, see the original PR.

**Comment by Overbryd** [comment]
Cool thanks for looking into it, and for your time.

It became a bit clearer now. I am merely a user of the library and not super involved with the implementation details yet, so I cannot comment much further on the implementation of `middleware/3`. On first sight, it is frankly hard to grasp what is going on.
