### ISSUE TITLE
Absinthe.Middleware.t is not a valid type

### ISSUE THREAD

**Issue by jparise** [absinthe-graphql/absinthe#291]
This type is referenced in a couple of places in the v1.3 branch:

```
lib/absinthe/schema.ex
217:  @callback plugins() :: [Absinthe.Middleware.t]

lib/absinthe/type/field.ex
44:  @type middleware_result :: {:middleware, Absinthe.Middleware.t, term}
```

... but it isn't defined anywhere.

**Comment by benwilson512** [comment]
When I glanced at my email your original title made me think this was a PR ;)

https://github.com/absinthe-graphql/absinthe/blob/v1.3/lib/absinthe/middleware.ex#L252 gives us a `Middleware.spec` type which is generally what we mean. Plugins specifically I may pull into their own behaviour since they really can only be accomplished with modules.

**Comment by benwilson512** [comment]
Fixed.
