### ISSUE TITLE
Possible to transform modify the parse / serialize behavior for "id" type?

### ISSUE THREAD

**Issue by weixiyen** [absinthe-graphql/absinthe#304]
I was wondering if it was possible to modify the parse / serialize behavior for the default "id" type, or would I have to specify my own custom scalar.

The reason is I have numeric IDs that I want to be represented as strings on the client side but integers on the server side.

Thanks!

**Comment by benwilson512** [comment]
There is not a way to customize it no, its behaviour is largely defined by the GraphQL spec itself. You can either use custom scalars, or use the upcoming middleware to transform the ids into integers prior to your resolvers.

Just FYI most GraphQL clients use base64 encoded values that decoded look like `user:123`.

**Comment by 0x6e6562** [comment]
I think my situation is similar to @weixiyen - on the client side IDs are strings and integers on the server side. Right now I have `String.to_integer/1` littered all over all of my resolvers. So should I hold off trying to genericize this myself and wait for the middleware pipeline to land? Or is the middleware concept in 1.3 sufficient to do pre-resolver transformation?

**Comment by benwilson512** [comment]
I'm not sure what middleware pipeline you're referring to other than the 1.3 middleware. 1,3 is in RC now, I highly recommend switching to it. I am on mobile at the moment but I will update later with an example.

**Comment by 0x6e6562** [comment]
@benwilson512 Sorry for the confusion - I was indeed referring to the middleware that has landed in 1.3 - if you could provide a example of how this would work for the `String.to_integer/1` conversion, that would be really appreciated :-)

**Comment by bruce** [comment]
@0x6e6562  Are you using Relay, locking you into the `ID` type (but with a data store with a hard integer requirement?)

If not, a custom `YourOwnID` scalar would the most straightforward way to handle this, not resolution middleware -- make it the responsibility of scalar parsing/serialization.

**Comment by 0x6e6562** [comment]
@bruce No, I'm not using Relay, just the vanilla Apollo redux client. IDs are stored as `BIGINT` on the server and to avoid JS truncation of large integer values, I'm passing all IDs over the wire as string values. So all I am looking for is a generic way to say if an argument is an ID, please parse it to an integer before hitting the DB.

Is there an example somewhere of how to do this with a custom scalar?

**Comment by tlvenn** [comment]
>I'm passing all IDs over the wire as string values

It does not solve your parsing issue but the `ID` type will always be serialisable as String so you should not have to do anything in that regard.

As for custom scalar, please have a look at this guide: http://absinthe-graphql.org/guides/custom-scalars/

You also might be interested in http://hashids.org/ to convert your IDs to truly opaque strings.

**Comment by bruce** [comment]
http://absinthe-graphql.org/tutorial/scalar-types/

The following will probably give you want you want (untested):

```elixir
scalar :your_id do
  parse fn input ->
    case Integer.parse(input.value) do
      {n, _} ->
        {:ok, n}
      :error ->
        :error
    end
  end
  serialize &Integer.to_string/1
end
```

Then use `:your_id` in Elixir code and `YourId` from JS. You can always set the `:name` option for your scalar type as well.

**Comment by bruce** [comment]
You can see several examples of custom scalars in `master`: https://github.com/absinthe-graphql/absinthe/blob/master/lib/absinthe/type/custom.ex

**Comment by 0x6e6562** [comment]
@bruce Your example works like a charm, I dropped this into my schema without any issues - many thanks :-)

**Comment by 0x6e6562** [comment]
@tlvenn Many thanks for the heads up about the custom scalars.

Also, the pointer to `hashids` is also very interesting and relevant. It would make the ids opaque and only really interpretable on the server side. In specific case, since I am only using integer IDs, the `hashids` site refers to [Optimus](https://jenssegers.com/67/id-transformation-with-optimus) using Knuth's integer hashing algorithm. So this gives you a number of choices.

The one question I can't quite answer is the motivation behind making the ids opaque. I get the fact that the opacity means you are not externalizing any object ids out into the wild. But `hashids` also states that you shouldn't be using this for security purposes in any case.

But this is going off topic from the original purpose of this issue.

**Comment by tlvenn** [comment]
If your database is using some sequences, you dont necessarly want to leak out some statistic about your domain, like for example, when I register a new user and I get assigned id `123` which give away that there is at most 123 users in the system.

If you use Base64 encode to make it opaque, it's completely trivial to reverse, hashids makes it a bit more difficult but at the same time might give you the wrong impression that it cant be done which is simply not true as you pointed out.

This kind of issue should probably be best addressed with the id generation system being used in the first place, so that instead of using a sequence, you could use UUID or a variation of snowflake for example.

So indeed, in the end, it seems pointless to try to opacify ids for the sake of not leaking out data. Converting from base 10 to an higher base system will compact ids however and given most GraphQL clients maintain a cache, there is a small benefit to keep those stringify IDs as short as possible.

**Comment by tlvenn** [comment]
And you can use something like https://github.com/whatyouhide/convertat to convert from/to arbitrary base.

**Comment by 0x6e6562** [comment]
@tlvenn - thanks for taking the time to discuss this :-)
