### ISSUE TITLE
Add config options to filter sensitive parameters out of the document

### ISSUE THREAD

**Issue by ChrisYammine** [absinthe-graphql/absinthe#320]
Hey absinthe team,

So first of all thanks for the great project, really digging it. 
I've come across a problem I have with the logging of queries which I'd like to report here and hopefully contribute a solution if possible.

Example:
```
11:52:30.758 request_id=vokr5qqclsqldanl01dgoiu51ugfheft [debug] ABSINTHE schema=nil variables=%{}
---
mutation {
    addUser(
      login: "sample@example.net"
      email: "fake@email.biz"
      first_name: "Jack"
      last_name: "Walsh"
      password: "2668709741"
    ) {
      id
      spree_api_key
    }
  }
---
```

I want to be able to configure the logger to filter sensitive parameters out of the document (`password` in the example above)

I was thinking something along the lines of:

config.exs
```elixir
config :absinthe, Absinthe.Logger, filtered_document_params: ~w(password)
```

Log output:
```
11:52:30.758 request_id=vokr5qqclsqldanl01dgoiu51ugfheft [debug] ABSINTHE schema=nil variables=%{}
---
mutation {
    addUser(
      login: "sample@example.net"
      email: "fake@email.biz"
      first_name: "Jack"
      last_name: "Walsh"
      password: [FILTERED]
    ) {
      id
      spree_api_key
    }
  }
---
```

Does this make sense to add? If you folks think so I would love to contribute the PR.

Cheers

**Comment by benwilson512** [comment]
Hey there. The way this is handled is by using variables. We already filter variables precisely as you're talking about.

It is not very easy to do this with document text itself, because logging happens prior to any kind of document parsing. Variables however are just JSON and are thus parsed prior to logging.

**Comment by ChrisYammine** [comment]
Ah okay, thanks @benwilson512 -- I didn't know about variables (not familiar with GraphQL at all)

I'll take a look! Cheers :)

**Comment by benwilson512** [comment]
Ahh, variables are excellent. You can think of them a lot like parameterized SQL queries. Here's how you'd use it in your case: 
```
mutation($login: String!, $email: String!, $first_name: String!, $last_name: String!, $password: String!) {
    addUser(
      login: $login,
      email: $email,
      first_name: $first_name,
      last_name: $last_name,
      password: $password
    ) {
      id
      spree_api_key
    }
  }
```

Then you send the variables alongside. There's some examples in the absinthe_plug tests here https://github.com/absinthe-graphql/absinthe_plug/blob/master/test/lib/absinthe/plug_test.exs#L90

If you're thinking that the variables thing can be a bit verbose, that's a fair concern :). That's why a common pattern with mutations is to do something more like

```
mutation($input: AddUserInput!) {
  addUser(input: $input) {
    id, spreeApiKey
  }
}
```

where `AddUserInput` is an input object in your schema.
