### ISSUE TITLE
Wrong ordering of returned fields

### ISSUE THREAD

**Issue by phyrog** [absinthe-graphql/absinthe#352]
The returned fields seem to be in descending order, no matter in which order they are specified in the query.

According to the [GraphQL spec](http://facebook.github.io/graphql/#sec-Serialization-Format), the returned data have the same order as the fields in the query:

> Serialization formats which can represent an ordered map should preserve the order of requested fields as defined by CollectFields() in the Execution section. Serialization formats which can only represent unordered maps should retain this order grammatically (such as JSON).
>
> Producing a response where fields are represented in the same order in which they appear in the request improves human readability during debugging and enables more efficient parsing of responses if the order of properties can be anticipated.

**Comment by bruce** [comment]
The previous version of the spec specified "must" vs "should," and the change was made after lengthy feedback by myself and @benwilson512 -- read https://github.com/facebook/graphql/issues/168. Since JSON object keys are (according to the JSON spec) unordered, this isn't on our roadmap to "fix" anytime soon. That said, we'd certainly welcome a PR for a custom serializer that adds this feature, provided it did so in a way that didn't noticeably degrade performance.

**Comment by bruce** [comment]
@benwilson512 Leaving open for you to make a comment if you'd like.

**Comment by phyrog** [comment]
Thanks for the feedback and the link to the discussion. Since I'm still new to Elixir and not familiar with the code base it's unlikely that I can produce a PR for this, but I can certainly have a look.

It's also not something that is really critical to me, it just surprised me today when using GraphiQL

**Comment by bruce** [comment]
Thanks, @phyrog, and if you could use any tips while looking through, feel free to join us in the #absinthe-graphql channel in the Elixir Slack; we're usually around and try to be helpful :-)

**Comment by benwilson512** [comment]
Yeah just to chime in, this is purely a function of how the `Absinthe.Phase.Document.Result` builds a result map, which is then used as an input to Poison. Elixir maps (and consequently Poison) don't have any order. This is definitionally fine for JSON objects.

If the ordering thing is a sticking point it would be very easy to replace the Result phase (it's a very simple phase) with something that built tuple lists instead of maps, and used a JSON codec that used some specific order.

**Comment by MartinKavik** [comment]
Hello guys! I would like to reopen this issue because it's a show-stopper for me and I'd like to fix it. And fix it right.

### Why reopen
- **A)** It breaks (Elm) frontend. Well, it's fixable ([blog post about it](https://medium.com/@eeue56/json-decoding-in-elm-is-still-difficult-cad2d1fb39ae) + it has to be fixed in Elm's GraphQL libraries), but I'd like to choose this option as the last one because solving order in backend seems to be more reasonable (see other points below)
- **B)** I think that preserving order is de facto standard in other libraries/services - e.g. http://www.graph.cool/
- **C)** Official paper recommend it (see the first post in this issue)
- **D)** I think it's more readable and predictable for testing or playing with e.g. GraphiQL

### How to fix it
- **1)** With **a list of tuples** where keys can be `string` ( @benwilson512 suggested in the previous post  ). I've written an experiment - see [github.com/MartinKavik/absinthe](https://github.com/MartinKavik/absinthe/commit/c5fa7e0f1a8fc49700d7c6a9f79bffbd5f54fcb8#diff-73cdd8db6a12e7474694c7098768488e):
  - `OrdMap` module is a group of helpers working with lists of tuples
  - `OrdMap` contains macro `o` which transforms `Map` to `List`   
  - I think some parts can be a little bit clumsy - e.g. Lists have problem with `Access` behaviour (see https://hexdocs.pm/elixir/Access.html -> `In order to be able to use the Access behaviour with custom data structures (which have to be structs)`
  - *Note*: tests in `test/lib/absinthe_test.exs` pass in that commit
- **2)** With **list of tuples** where keys are atoms (= `Keyword`).
  - maybe the similar problem with `Access` behaviour
  - I don't know if it's relevant to Absinthe's implementation, but this can be potential problem: https://stackoverflow.com/a/34447274
- **3)** With `OrderedMap` ([github.com/jonnystorm/ordered-map-elixir](https://github.com/jonnystorm/ordered-map-elixir/blob/master/lib/ordered_map.ex))
  - It seems like using a list of tuples but with added complexity
  - It implements `Access` behaviour
- **4)** Add a meta field to maps during parsing of requested query
  - e.g. `%{"id" => 123, "name" => "John Doe", "_order" => ["id", "name"])]`
  - conversion from `Maps` to `Lists` will be processed  just before serialization to JSON
  - I don't know if it's doable and clean solution but imho the least "invasive" one
  - inspired by `OrderedMap` keys storage
- **5)** Use some structure from Erlang world
  - `orddict` was removed from Elixir
  - maybe use `array`?
  - or some custom solution based on `gb_trees` or on some GitHub repos (e.g. https://github.com/knutin/bisect)

### Discussion
  I want to write a proper solution and send PR. Could you direct me to the right implementation? Thanks.

**Comment by benwilson512** [comment]
Hey @MartinKavik, I do think it's probably worthwhile to document a solution. Absinthe maintains the order of the fields throughout the entire process until the very last phase where we build the maps used to produce JSON.

A solution then simply consists of two things:

1) A slightly modified Result phase that produces lists of tuples instead of maps
2) Use of a JSON codec that supports lists of tuples like `:jiffy`.

Ultimately it's a pretty limited amount of changes, and I would consider including an `OrderedResult` phase within Absinthe itself that, while not the default, could be swapped in if desired.

We could add a guide page on Codecs or something that coffered how to switch result phases and configure something like `:jiffy`.

**Comment by MartinKavik** [comment]
@benwilson512: 
- So I'll create `OrderedResult` and send PR
- Then I'll help with writing docs
- Then we can switch to `OrderedResult` as the default option
Is it ok for you?

**Comment by benwilson512** [comment]
I am hesitant to change make it the default, since lists of tuples are incompatible with the de-facto standard Elixir JSON codec:  Poison. It's been my stance since the beginning of this that it's perfectly fine to require ordered results, but it's less fine to require ordered results and call it JSON. The JSON spec could not be clearer that objects are to be considered unordered, and the argument that they're ordered because when it comes over the wire the bytes have an order does not hold water.

I can get behind making it easier for people to achieve the output that they desire from Absinthe, but I am disinclined to push a change that would break 99% of everyone's setup because certain clients insist on enforcing properties that the JSON spec does not promise.

**Comment by MartinKavik** [comment]
@benwilson512 You wrote: `lists of tuples are incompatible with the de-facto standard Elixir JSON codec: Poison` - so I've written module which wraps key-value list [MartinKavik/ord_map](https://github.com/MartinKavik/ord_map) and encoder for Poison [MartinKavik/ord_map_encoder_poison](ord_map_encoder_poison). (Feedback very welcome)

Then, I've integrated **ord_map** to **absinthe** and **ord_map_encoder_poison** to **absinthe_plug**. So it's now possible to switch to ordered results just with **`config :absinthe, ordered: true`** in *config.exs*.

I've tried it with **absinthe_tutorial** and it seems working fine (a short [commit](https://github.com/MartinKavik/absinthe_tutorial/commit/4de2ce7ad4a629b22fe344e51ff934f7c2ed18a8) with changes in my fork).

I'll send PRs to **absinthe** and **absinthe_plug** for code reviews in a moment.

When PRs will be ok and merged I can write a short article `Using with Elm` to docs (btw nice new docs and it was a good idea to add the link to book into it - I've just bought it.) 

(OT: links to absinthe-graphql.org are dead in Readme)

**Comment by bruce** [comment]
@MartinKavik Am _very_ interested in the "Using with Elm" guide. I'll let @benwilson512 review the plan with regard to use of a config value for this.
