### ISSUE TITLE
Schema middleware callback affecting introspection

### ISSUE THREAD

**Issue by benwilson512** [absinthe-graphql/absinthe#565]
See https://github.com/absinthe-graphql/absinthe_plug/issues/159#issuecomment-399488012

**Comment by bgentry** [comment]
Hi @benwilson512, unfortunately this is one more issue I encountered when upgrading to v1.5. I had an issue all filled out on this before I stumbled upon this existing issue, so I'll just re-paste that description since it covers everything:

### Environment

* Elixir version (elixir -v):

   ```
   Erlang/OTP 22 [erts-10.7] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe] [dtrace]
   
   Elixir 1.10.2 (compiled with Erlang/OTP 22)
   ```

* Absinthe version (mix deps | grep absinthe):

   ```
   * absinthe 1.5.0-rc.4 (https://github.com/absinthe-graphql/absinthe.git) (mix)
   * absinthe_relay 1.5.0-rc.0 (https://github.com/absinthe-graphql/absinthe_relay.git) (mix)
   * absinthe_sorting_codec 1.0.1 (Hex package) (mix)
     locked at 1.0.1 (absinthe_sorting_codec) d865e516
   * absinthe_plug 1.5.0-rc.2 (Hex package) (mix)
     locked at 1.5.0-rc.2 (absinthe_plug) 65720d6a
   * absinthe_phoenix 1.5.0-rc.0 (Hex package) (mix)
     locked at 1.5.0-rc.0 (absinthe_phoenix) 9a76cda0
   * Client Framework and version (Relay, Apollo, etc):
   ```

### Expected behavior

I expected to see my entire JSON schema dumped as in v1.4 when I run this command:

```
mix absinthe.schema.json --schema MyApp.Web.GraphQL.Schema --json-codec AbsintheSortingCodec --pretty
```

### Actual behavior

Instead, I am blocked by an authentication error from my middleware which I did not alter during the course of the v1.5 upgrade:

```json
{
  "data": {
    "__schema": null
  },
  "errors": [
    {
      "locations": [
        {
          "column": 3,
          "line": 2
        }
      ],
      "message": "unauthenticated",
      "path": [
        "__schema"
      ]
    }
  ]
}
```

Is it possible that the schema introspection was changed in a way where it is now running through the normal resolution code path, rather than running in some process which never actually executes the resolution process? I assume something must have changed in this regard for v1.5, perhaps with #503?

### Relevant Schema/Middleware Code

```elixir
defmodule MyApp.Web.GraphQL.Middleware.Authentication do
  @behaviour Absinthe.Middleware

  def call(resolution, _config) do
    case resolution.context do
      %{current_user: _} -> resolution
      _ -> Absinthe.Resolution.put_result(resolution, {:error, "unauthenticated"})
    end
  end
end
```

I'm going to give the workaround linked here a try to see if that does the trick for now 🤞

**Comment by bgentry** [comment]
The workaround seems to have changed slightly, this worked for me:

```elixir
def middleware(
        middleware,
        %{__reference__: %{module: Absinthe.Phase.Schema.Introspection}},
        _object
      ) do
    middleware
  end
```

**Comment by benwilson512** [comment]
> Is it possible that the schema introspection was changed in a way where it is now running through the normal resolution code path, rather than running in some process which never actually executes the resolution process?

Yeah, introspection was sort of special cased in 1.4, but this made a bunch of stuff way harder than it should have been.

However, I agree that avoid introspection manually in `def middleware` is sort of a pain. Let me think about what makes sense here.

**Comment by benwilson512** [comment]
OK after messing with this, I think we should just have Absinthe not pass introspection fields to `def middleware`. If you want to manipulate introspection fields yourself this is easily achievable now via `hydrate` or custom schema building phases.

**Comment by youroff** [comment]
Just ran into an issues related to this. I was trying to come up with a nice way to disable introspection (but keep `__typename`, which probably should be in its own phase?), and first  idea was to use middleware, since `__schema` and `__type` are just fields, right? But it didn't work due to this special treatment of introspection fields. Then I replaced the Phase with a patched version of `Absinthe.Phase.Schema.Introspection` and it broke some middleware, because now it's a different module that exposes introspection conditionally (in a compile-time config). I think it would be better to keep it consistent and explicit, meaning, to let users filter fields while attaching middleware (i.e. using guard `when field not in [:__schema, :__type, :__typename]`), and make introspection fields just regular fields.
