### ISSUE TITLE
Non-UTC datetimes are considered invalid

### ISSUE THREAD

**Issue by 1player** [absinthe-graphql/absinthe#700]
The DateTime parser in Absinthe.Type.Custom:
https://github.com/absinthe-graphql/absinthe/blob/cf46de10c10e155b413e8609d49e32da2999a839/lib/absinthe/type/custom.ex#L77-L78 returns `:error` if a non-UTC datetime (but still with timezone information) is passed to it.

Ex: `2019-03-30T17:19:00Z` is valid, `2019-03-30T17:19:00+01:00` is not.

What is the rationale behind that design choice? `DateTime.from_iso8601` converts the date to UTC in the second element of the return tuple, so non-UTC date strings are in theory parseable.

```
iex(1)> DateTime.from_iso8601("2019-03-30T17:19:00Z")
{:ok, #DateTime<2019-03-30T17:19:00Z>, 0}
iex(2)> DateTime.from_iso8601("2019-03-30T17:19:00+01:00")
{:ok, #DateTime<2019-03-30 16:19:00Z>, 3600}
```

In my project I've copy-pasted Absinthe.Type.Custom to add support for non-UTC datetimes, I'd like to know if I'm missing something and I should enforce UTC datetimes on my clients instead.

**Comment by conradwt** [comment]
`DateTime.from_iso8601` is a function which comes from the Elixir project.  Thus, you may want to file an issue there.

**Comment by 1player** [comment]
There is no issue on DateTime.from_iso8601. The function works as intended.

My issue is related to the DateTime type parser in Absinthe.Type.Custom, which does not accept non-UTC date strings.

**Comment by benwilson512** [comment]
@1player What value should the scalar return for non utc date times? Keep in mind, an offset is not the same thing as a timezone.

**Comment by 1player** [comment]
> What value should the scalar return for non utc date times? Keep in mind, an offset is not the same thing as a timezone.

I reckon a valid DateTime object. The common best practice is converting to UTC at the edges of the application, and dealing only with UTC objects internally, which is what my application does.

The only piece of information you'd lose is the original time offset, which I do not care about, and I doubt many applications require to know that information. My frontend client when it's doing a request encodes a JS Date object into a ISO8601 string, which is not always in UTC timezone. I would expect my GraphQL backend to be able to handle those.

As stated in the original post, `DateTime.from_iso8601` already does its job without any loss of information, and since `2019-03-30T17:19:00Z` == `2019-03-30T16:19:00+01:00`, I do not see why Absinthe should enforce UTC datetimes as input.

**Comment by benwilson512** [comment]
Absinthe is a relatively conservative project, we wanted the built in defaults to avoid "gotchas". In this case the concern was that dropping the offset, while that may not affect you personally, would still constitute a loss of information that may negatively affect people in surprising ways. I'm happy to revisit this discussion, but that's the motivation.

I'm happy to revisit this, although really I think the way forward here is to create a `:utc_datetime` type that does this coercion. The `utc_` prefix makes this a bit more explicit, and in line with behaviors that have developed in Ecto since these types were first written. The existing `:datetime` type would remain as is but be deprecated.

**Comment by seivan** [comment]
@benwilson512 The real "gotcha" here is what Absinthe is actually doing invalidating what essentially constitutes a valid format. 

In other words, if  someone sends valid request containing `2019-03-30T17:19:00+01:00` it shouldn't automatically be invalidated,  I mean that's the whole purpose of the standardization. 

It's both a valid `iso8601` format and something `DateTime.from_iso8601` actually handles out of the box. 

That being said, there is tangible loss of information here but that applies either way. If someone sends UTC or not, there is still a need to also send the actual timezone with it. 
accepting **only** UTC doesn't actually prevent loss of information, but granted it does clarify it.

**Comment by benwilson512** [comment]
Hi @seivan, this is what I mean by information loss:

```
DateTime.from_iso8601("2019-03-30T17:19:00+01:00")
{:ok, #DateTime<2019-03-30 16:19:00Z>, 3600}
```
See how the date time does not contain the provided offset information? Information was definitely lost there.

This is still true today actually even with the improvements to Elixir's standard library handling of timezones:
```
DateTime.from_iso8601("2019-03-30T17:19:00+01:00")
{:ok, ~U[2019-03-30 16:19:00Z], 3600}
```

Offsets are not the same thing as timezones, so knowing the offset doesn't let you derive the timezone. I realize this only addresses part of your argument, but I think it's important that we're clear on the information loss part.

**Comment by seivan** [comment]
@benwilson512 No I understand that completely. Offset are irrelevant since they are static as opposed to actual timezones a la´ "Europe/Paris" that would follow DST and other policy changes. So I get that part, it's very clear to me. 


If a client sends you `"2019-03-30T17:19:00+01:00"` or `"2019-03-30T17:18:00Z" (UTC)`
They still have to send a time zone, regardless of the validations put in place here. 

What I am trying to say is that the current situation has just moved the conversion to happen on the client. 
They got `"2019-03-30T17:19:00+01:00"`, convert it to UTC which becomes `"2019-03-30T17:18:00Z"` and send it. The loss of information is **still** happening, it hasn't gone away, Absinthe has (and can't) prevent that nor should it be expected to.

The correct way is to *also* send the time zone, regardless if the client is sending UTC converted `iso8601` or "regular" `iso8601`.

Absinthe shouldn't take it upon itself to prevent non UTC datetimes as long as it fits `iso8601` standard.
The loss of information is happening *because* the timezone isn't sent with it, again I'm not referring to the offsets. 

In our case we would send `"2019-03-30T17:19:00+01:00"` and "Europe/Paris".
`DateTime.from_iso8601("2019-03-30T17:19:00+01:00")` via Absinthe would convert that to UTC and we also get the timezone associated if we were for some reason need to map that back. 

It's not a big deal to convert it on the client side, in fact, I think the API today (for browsers at least) does it already, calling `date.toISOString()` but it's an unnecessary step.

**Comment by benwilson512** [comment]
That's a fair point. PR welcome, we'll include the change in the 1.5 release.

**Comment by seivan** [comment]
@benwilson512 I hope I didn't wear you down :) 

What would be a useful PR, just removing the error for anything creating an offset, or something that tackles the `time + zone` as two fields?

**Comment by benwilson512** [comment]
> I hope I didn't wear you down :)
No not at all, your point that the "data loss" was inevitable and we'd just moved it to the client was compelling. The offset isn't the timezone, so that has to be passed anyway.

I think the PR should just remove the error for non 0 offsets. You can't have a scalar that uses two different graphQL fields so supporting something that was first class time + zone would have to be a larger project.

**Comment by seivan** [comment]
Fixed in https://github.com/absinthe-graphql/absinthe/pull/879
