### ISSUE TITLE
SDL Compilation Error with Directives

### ISSUE THREAD

**Issue by maennchen** [absinthe-graphql/absinthe#703]
If submitting a bug, please provide the following:

### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.8.0 (compiled with Erlang/OTP 21)
```

* Absinthe version (mix deps | grep absinthe):

```
* absinthe 1.5.0-alpha.4 (Hex package) (mix)
  locked at 1.5.0-alpha.4 (absinthe) fa6dbd49
* absinthe_plug 1.4.6 (Hex package) (mix)
  locked at 1.4.6 (absinthe_plug) ac5d2d3d
* absinthe_phoenix 1.4.3 (Hex package) (mix)
  locked at 1.4.3 (absinthe_phoenix) cea34e7e
```

* Client Framework and version (Relay, Apollo, etc):

None

### Expected behavior

No errors in compilation

### Actual behavior

```
== Compilation error in file lib/acme_api/schema.ex ==
** (Absinthe.Schema.Notation.Error) `import_sdl` could not parse SDL:
An unknown error occurred during parsing: argument error ([])
    lib/invest_api/schema.ex:9: (module)
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:208: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

### Relevant Schema/Middleware Code

Adding this file with `import_sdl`: https://github.com/APIs-guru/graphql-faker/blob/master/src/fake_definition.graphql

**Comment by benwilson512** [comment]
There are a large number of missing SDL features right now, I'm not sure we want to do an issue for each. @bruce thoughts?

**Comment by bruce** [comment]
@benwilson512 I think this is okay, provided we apply the milestone for tracking. It's helpful to have additional eyeballs on specific SDL issues as I try to address them, so feel free to assign any to me.

(Perhaps, also, enough people are using 1.5—despite alpha status—in production that what's an "issue" and what's a distraction to active development is a bit fuzzy. Our fault, I'm thinking, due to our extended development timeline for this release. 😅)

@maennchen Thank you for this report. ✨ Feel free, btw, to report any future SDL errors as PRs with failing test cases, if it's convenient and you can generalize the schema used.

**Comment by binaryseed** [comment]
The linked PR looks like it closes this issue out...
