### ISSUE TITLE
[Proposal] Optimization - de-duplicate storage of active subscription documents

### ISSUE THREAD

**Issue by darrenclark** [absinthe-graphql/absinthe#773]
## Problem

Our application has a few pretty large GraphQL subscription operation (very rough estimate of the `Absinthe.Blueprint` for it was ~1MB).

And, as it currently stands, the documents are being stored along side the subscription in the Registry (https://github.com/absinthe-graphql/absinthe/blob/5b5079f03402f482c5f52a35efc263a5a6ccaf64/lib/absinthe/subscription.ex#L112).

Given the above points, our application can easily OOM if we have a significant amount of active subscriptions.  Many of our documents are the exact same from each user, so I was thinking there could be some memory savings by moving the documents outside of the `Registry` & deduplicating them.

## Proposal

Store the documents outside the of `Registry` in an ETS table.  They'd be keyed off the `doc_id` (in the line of code linked above), and reference counted.

Was thinking the records would look something like:

```elixir
{doc_id, ref_count, %Absinthe.Blueprint{...}}
```

## Thoughts?

Before I start implementing this, wanted to get some thoughts.

1. 👍 / 👎 ?
1. Would this be useful enough to be integrated into Absinthe?
    - not sure if this is pretty specific to our app or not
    - if not, is there some extension points we could add to Absinthe to allow our app to do something like this?
1. Any alternatives for reducing memory usage?

**Comment by benwilson512** [comment]
Hey @darrenclark. I would absolutely love to de-duplicate the blueprints in memory, but I can't come up with a way to do this that doesn't introduce significant bottlenecks around the `ref_count` value. I'm happy to hear any proposals that solve that issue.

If we look at the problem more generally, perhaps the default for Absinthe should be to store the raw subscription string and variables in the registry instead of the parsed value. This will increase the cost of running subscriptions a little, but the memory usage may be a lot lower, I need to measure.

**Comment by benwilson512** [comment]
I should add that some of the data provided in this issue https://github.com/absinthe-graphql/absinthe_phoenix/issues/61 indicates that there may be a bug in the latest versions of 1.5 that increases the memory usage beyond what it should be. I hope to have time to investigate that further today.

**Comment by darrenclark** [comment]
Ahh yes, I'll give it some more thought and (hopefully) try to throw something together.

Will check out that PR too, thanks!

**Comment by binaryseed** [comment]
> I would absolutely love to de-duplicate the blueprints in memory, but I can't come up with a way to do this that doesn't introduce significant bottlenecks around the ref_count value.

What about `persistent_term` for storing blueprints?

* http://erlang.org/doc/man/persistent_term.html

It's heavily optimize for high read / rare update situations - lookups take no locks & do no memory copying! Seems like a possible way to avoid sending around these gigantic structs that never change

Only caveat is that it's only in OTP-22, but it could be conditionally applied

**Comment by benwilson512** [comment]
@binaryseed I considered it, and we should probably benchmark it. The concern however is that `put` and `delete` operations can trigger global garbage collection in all the processes, which is bad. The subscription store needs to be well optimized for retrieval, insertion, as well as deletion, since at least in the main case where subscriptions support a front end via websockets, clients come and go frequently.

**Comment by binaryseed** [comment]
Makes sense... This might be a tangent, but is there anywhere else in Absinthe that you think might benefit from the technique? I know the schema structs are passed around quite a lot in resolvers

**Comment by benwilson512** [comment]
@binaryseed Absinthe schemas use the traditional optimization technique of baking everything into a literal, which achieves the same shared memory optimization and is even slightly faster. Because schema building is achieved with pipelines now though you could definitely switch out the "compile to an elixir module" phase with a phase that shoved everything into persistent term. This would be what you'd want if you were accepting user built schemas probably.

**Comment by benwilson512** [comment]
Closing this for now, feel free to reopen @darrenclark if you have updates.
