### ISSUE TITLE
Feature Request: Query Complexity Equivalent for Errors

### ISSUE THREAD

**Issue by ACBullen** [absinthe-graphql/absinthe#826]
I've been working on a pipeline stage to address this for the project I am working on, but I figure the functionality could be broadly useful.

### The Problem

A fairly simple malicious query can result in a response many times its size, which in turn could be used as a DoS vector. For example the query `{q}` gets the response: 
```
{
  "errors": [
    {
      "locations": [
        {
          "column": 0,
          "line": 1
        }
      ],
      "message": "Cannot query field \"q\" on type \"RootQueryType\"."
    }
  ]
}
```
Which can be expanded to `{q\nq}` to receive an error back with two error entries with only the line number changed in the error. Add in a few thousand more q's and newlines and the server will happily build a gigantic response and stream it back over several seconds. Spin up a couple processes sending the malicious query repeatedly and the server eventually grinds to a halt.  Similar to preventing users from requesting overly-complex documents with `max_query_complexity`, being able to provide a maximum to the number of errors returned by the endpoint seems to be a useful lever to provide.

### Solution thoughts

In my current fiddling with the issue. I have been inserting a pipeline stage after `Absinthe.Phase.Document.Result` which reduces over the result and imposes a limit on the number returned (when provided). But I think integrating that logic into `Absinthe.Phase.Document.Validation.Result` might be a more appropriate place to handle things.

If this seems like a worthwhile addition, I can work on a quick port of my current solution into a PR here. Thoughts?

**Comment by benwilson512** [comment]
Hi @ACBullen this is a very interesting question. I am definitely on board with the idea of enabling configurable limits on the number of errors that are addressed in a response. I think emitting metrics (perhaps via telemetry) about errors are likely good as well, because I think the ideal way to handle this is at the request level. That is to say, you could wire those metrics into a plug based request limiter, and if allow users eg 10 errors per second or something, and start rate limiting their requests if they exceed that.

I think this helps mitigate against having every phase that deals with errors have to concern itself with how many errors are generated. I'm sure someone could craft pathological documents that produce an arbitrary number of GraphQL syntax errors for example, and making the parser worry about that could be quite challenging.

**Comment by ACBullen** [comment]
Ok. I think I see your point about it not really being the parser's business. Thanks for the input, I'll close this out and tinker with addressing it elsewhere in the process.
