### ISSUE TITLE
Absinthe subscription schema non null error on an optional field.

### ISSUE THREAD

**Issue by simke9445** [absinthe-graphql/absinthe#866]
Greetings Absinthe team,

I'm having trouble using the subscriptions module from Absinthe.

What's happening is that when I try to publish a subscription I get a GraphQL validation error for nested fields of an optional object field.

To illustrate this better:
- I have Notification and Creator types and a notification_created subscription
- Notification schema has a creator field - which is optional, i.e. no non_null present here
- notification_created subscription returns a Notification type as response

notification_created subscription
```
  object :notification_subscriptions do
    field :notification_created, non_null(:notification) do
    ...
    end
  end
```

Creator schema (reduced):
```
  object :creator do
    field(:id, non_null(:id))
  end
```

Notification schema (reduced):
```
  object :notification do
    field(:creator, :creator)
  end
```

Expected behaviour:
- Specifying creator field within the subscription query would return the field as null if the emitted value is null for creator as well.

```
subscription {
  notificationCreated {
     creator {
       id
     }
  }
}
```

Actual behaviour:
- Response I'm getting seems like it tries to validate the creator schema even though the creator field is null.
```
notificationCreated {
  __typename: "Notification"
  creator: null
}

message: "Cannot return null for non-nullable field"
path: ["notificationCreated", "creator", "id"]
0: "notificationCreated"
1: "creator"
2: "id"
```

Environment:
- Elixir version 1.9.1
- Absinthe version: 1.4.16
- Client Framework and version: React-Apollo 2.4

Does anyone have an idea what might be causing the issue?

What makes this even wierder is that when I make creator id field nullable the response looks like this:
```
notificationCreated {
  __typename: "Notification"
  creator: {
     id: null
  }
}
```

**Comment by benwilson512** [comment]
Hi @simke9445. I'm pretty sure that the issue is related to the presence of an `%Ecto.AssociationNotLoaded{}` struct on the `:creator` key of your `notification` struct. If you look at the error closely, you'll notice that it isn't complaining about a null creator, it's complaining about a null creator _id_. This means that it thinks you've given it a creator. If you are using the default middleware on the `field(:creator, :creator)` and not something like `dataloader`, then when Absinthe does `Map.get(notification, :creator)` the return value will be `%Ecto.AssociationNotLoaded{}`, which Absinthe then treats as a creator value. Then it tries to do `Map.get(%Ecto.AssociationNotLoaded{}, :id)` which returns null.

You should either preload the creator field, update the creator resolver manually to handle `%Ecto.AssociationNotLoaded{}`, or use something like `dataloader` as the resolver which knows to do a lookup.
