### ISSUE TITLE
Field names not accepted when using custom language conventions

### ISSUE THREAD

**Issue by 1player** [absinthe-graphql/absinthe#907]
### Environment

* Elixir version (elixir -v): 1.10.2
* Absinthe version (mix deps | grep absinthe): 1.5.0-rc.5
* Client Framework and version (Relay, Apollo, etc): Apollo

I've tried migrating my app from 1.4 to the latest 1.5 RC. We're using a custom adapter to convert Elixir's `boolean?` fields to `isBoolean` and viceversa.

Starting the app with 1.5 shows a few errors stating that `Field name "boolean?" has invalid characters.`

The adapter is pretty stupid and is basically a copy of Absinthe.Adapter.LanguageConvention with added:

```
# Workaround for isDeprecated field used in introspection
  def to_internal_name("isDeprecated", _role), do: "is_deprecated"

  def to_internal_name(camelized_name, _role) do
    final_name =
      camelized_name
      |> Macro.underscore()

    if String.starts_with?(final_name, "is_") do
      String.trim_leading(final_name, "is_") <> "?"
    else
      final_name
    end
  end

...

def to_external_name(underscored_name, _role) do
    if String.ends_with?(underscored_name, "?") do
      ("is_" <> underscored_name)
      |> String.trim_trailing("?")
    else
      underscored_name
    end
    |> Utils.camelize(lower: true)
  end
```

The question is:

1. How do I replicate this behaviour in 1.5?
2. Is there a better way of converting `boolean?` to `isBoolean` with 1.5 without having to change all my code? The goal is to pass native Elixir structs to Absinthe without having to convert those field names manually.
3. Alternatively, can we add a `source` option to field, like Ecto does? `field(:is_boolean, :boolean, source: :boolean?)`

**Comment by binaryseed** [comment]
Hello! This is happening because of the `Absinthe.Phase.Schema.Validation.NamesMustBeValid` validation phase. It's just implementing the GraphQL spec which only allows a limited set of characters in names.

https://graphql.github.io/graphql-spec/June2018/#sec-Names

You can keep your existing behavior by implementing the `pipeline/1` callback in your `Absinthe.Schema` module, and using `Absinthe.Pipeline.without/1` to remove the phase.

This is noted in the upgrade guide:

https://hexdocs.pm/absinthe/1.5.0-rc.5/v1-5.html#content
