### ISSUE TITLE
Node flags are not available in resolver

### ISSUE THREAD

**Issue by dlindenkreuz** [absinthe-graphql/absinthe#964]
### Environment

* Elixir version (elixir -v): Elixir 1.10.4 (compiled with Erlang/OTP 23)
* Absinthe version (mix deps | grep absinthe): 1.5.2
* Client Framework and version (Relay, Apollo, etc): n/a

### Expected behavior

When using `Blueprint.put_flag` on a field definition as part of expanding a directive, that flag should be accessible in the resolver later on.

### Actual behavior

In the resolution struct that is passed to the resolver, the `definition` property has the type `Absinthe.Blueprint.Document.Field`. Somehow, the original `Absinthe.Blueprint.Document.FieldDefinition` that the directive sees as `node` and uses for setting the flag, is gone. Although the `Field` type has a `flags` array, that array is always empty.

### Relevant Schema/Middleware Code

```graphql
# schema.graphql
type Query {
    units: [Unit!]! @all
}
```

```elixir
defmodule FooApp.Schema do
  use Absinthe.Schema
  alias Absinthe.Blueprint

  @prototype_schema FooApp.SchemaPrototype

  import_sdl(path: Path.join(__DIR__, "schema.graphql"))

  def hydrate(%{identifier: :units}, [%{identifier: :query} | _]) do
    {:resolve, &__MODULE__.resolve_units/2}
  end

  def hydrate(_, _), do: []

  def resolve_units(_, _, resolution) do
    # %Absinthe.Blueprint.Schema.Field{...}
    # should have :resolve_all flag but has none
    resolution.definition |> IO.inspect(label: "in resolver")
    {:ok, %{id: 123}}
  end
end
```

```elixir
defmodule FooApp.SchemaPrototype do
  use Absinthe.Schema.Prototype
  alias Absinthe.Blueprint

  directive :all do
    on([:field_definition])
    expand(fn _, node →
      # %Absinthe.Blueprint.Schema.FieldDefinition{...} (note the difference!)
      node |> IO.inspect(label: "directive expansion")
      Blueprint.put_flag(node, :resolve_all, __MODULE__)
    end)
  end
end
```

**Comment by binaryseed** [comment]
I think that actually this isn't a _bug_ as much as missing feature, we just don't have full support for "Type System Directives" yet in Absinthe.

The resolver's `field.definition` is correct, it should be the `Schema.Field` - any directives that _it_ has would have come from the user's Query, as "Executable Directives" on a `:field`

We're tracking the "Type System Directives" feature here: #1003 , but there's a good bit of design work to do before we can support it.

@benwilson512 Does this sound right to you? I'm going to close this since it's covered by that issue, but let me know if you think my assessment is correct...

**Comment by binaryseed** [comment]
I think you might want to consider using Absinthe's `meta` feature in the meantime, it isn't part of the SDL syntax, but...

Type System Directives _can_ be accessed during `hydrate`, since the first argument to them is the `*Definition` struct.

Based on that you could add some `:meta` in that `hydrate` that would then be available in the resolver under `resolution.definition.schema_node.__private__[:meta]`.

```elixir
  def hydrate(%{identifier: :units} = definition, [%{identifier: :query} | _]) do
    [
      {:meta, meta_from_definition(definition)},
      {:resolve, &__MODULE__.resolve_units/2}
    ]
  end
```
