### ISSUE TITLE
Bug: inconsistent generated object field name, when including numbers

### ISSUE THREAD

**Issue by matehat** [absinthe-graphql/absinthe#976]
### Environment

* Elixir version (elixir -v): 1.10.4
* Absinthe version (mix deps | grep absinthe): 1.5.3
* Client Framework and version (Relay, Apollo, etc): 

### Expected behavior

Given an object like this:

```elixir
object :input_address do
    field(:area_level_1, non_null(:string), name: "areaLevel1")
    field(:area_level_2, :string, name: "areaLevel2")
    field(:area_level_3, :string, name: "areaLevel3")
    ...
end
```

When running `mix absinthe.schema.sdl`, it generates a schema like this:

```graphql
type InputAddress {
  areaLevel1: String!
  areaLevel2: String
  areaLevel3: String
  ...
}
```

When using it in a query (NodeJS's `graphql` package), 

```graphql
mutation CreateWorkplaceMutation(
    $name: LimitedString200!
    $inputAddress: InputAddress!
    $organizationId: ID!
    $main: Boolean
  ) {
    createWorkplace(
      workplace: {
        name: $name
        inputAddress: $inputAddress
        organizationId: $organizationId
        main: $main
      }
    ) {
      operationTime
      identifier
      eventId
    }
  }
```

with variables:

```json
{
      "name": "Runte, DuBuque and Considine",
      "organizationId": "56b8d3d4-0720-11eb-b527-0242ac12000f",
      "inputAddress": {
        "postalCode": "92430",
        "country": "Russian Federation",
        "areaLevel1": "South Dakota",
        "areaLevel2": "Avon",
        "areaLevel3": "Cambridgeshire",
        "locality": "Port Dewitt",
        "sublocality": "Berkshire",
        "route": "Hyatt Plains",
        "streetNumber": "9805",
        "room": "Port 813",
        "formatted": "972 Avery Track Suite 475",
        "geolocation": { "latitude": 24.2698, "longitude": 64.7459 }
      },
      "main": false
}
```

It was supposed to work.

### Actual behavior

I get a very confusing error:

```
Argument "workplace" has invalid value {name: $name, inputAddress: $inputAddress, organizationId: $organizationId, main: $main}.
    In field "inputAddress": Expected type "InputAddress!", found $inputAddress.
    In field "areaLevel1": Expected type "String!", found null.
    In field "areaLevel1": Unknown field. Did you mean "areaLevel2", "areaLevel3", or "areaLevel1"?
    In field "areaLevel2": Unknown field. Did you mean "areaLevel1", "areaLevel3", or "areaLevel2"?
    In field "areaLevel3": Unknown field. Did you mean "areaLevel1", "areaLevel2", or "areaLevel3"?
```

Seems like Absinthe assumes `area_level_1` should be sent over as JSON name `areaLevel1`, but does not recognize it as such ..

- I tried using the `name: "areaLevel1"` argument to the `field` macro, no luck.
- I could get a workaround to work by passing `areaLevel_1` in the JSON (so, _not_ trusting  the generated SDL), but since I'm using the generated SDL schema to generate types in Typescript, it messes up the client big time.

Any clue?

**Comment by benwilson512** [comment]
The issue is that Absinthe relies on the built in `Macro.underscore` and `Macro.camelize` functions, and these functions are not inverses of one another. Specifically, both of these inputs result in the same output:

```
iex(2)> Macro.camelize("foo_1")
"Foo1"
iex(3)> Macro.camelize("foo1") 
"Foo1"
```

However, if you pass this output into `underscore`, you only get a specific one of those back:

```
iex(4)> Macro.underscore("foo1")
"foo1"
```

Thus in your schema you need to do: `field(:area_level2)`. This way, when you get `areaLevel2` from the query, it is underscored to `area_level2` and then matched against `area_level2` and is found.

**Comment by matehat** [comment]
@benwilson512 Any idea why the `name:` argument could not be taken into account? Isn't there a way to force absinthe to use a certain name in GraphQL?

**Comment by benwilson512** [comment]
This is something we hope to address in a 2.0 release. In 1.X, the mapping of external values to internal values is handled via Adaptors. You can plug your own adapter in that does the mapping any way you like. The theory is that you can use one schema on multiple endpoints, each with different camelcase / underscore conventions, instead of hardcoding into the schema. See https://hexdocs.pm/absinthe/adapters.html#content for more info.
